name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nyquist7/scorobot:$(date -Format "yyyyMMddHHmm") --tag nyquist7/scorobot
    - name: Push the Docker image
      run: docker push nyquist7/scorobot:$(date -Format "yyyyMMddHHmm")